#!/bin/bash

echo "Creating hubot in $1"
set -x
cd /home/hubot/hubots
mkdir -p $1
cd $1
# npm install coffee-script yo generator-hubot hubot
echo y | yo hubot --defaults
npm install hubot-slack --save