#!/bin/bash

echo "Creating hubot in $1"
set -x
cd /home/hubot/hubots
mkdir -p $1
cd $1
# npm install coffee-script yo generator-hubot hubot
echo y | yo hubot --defaults
npm install hubot-slack --save
npm install hubot-redis-brain --save
# Don't do this, because it will cause our scripts to fail when running without redis
#echo '[ "hubot-redis-brain" ]' > external-scripts.json
