#!/bin/bash

if [ -f hubots/current-hubot.txt ];
  then
  CURRENT=$(cat ./hubots/current-hubot.txt)
  run-hubot $CURRENT
else
  echo "Put the name of the hubot you want to run in hubot/hubots/current-hubot.txt"
fi
