#!/usr/bin/env ruby

require 'fileutils'

def usage
  puts "USAGE: create_android_with_gradle <project-name> <package-name>"
  puts
  puts "Use only [a-zA-Z0-9] in the project name"
  puts "Package name should be the java language package format: com.example.mything"
  puts
  exit	 
end 

project = ARGV.shift
package = ARGV.shift
if not project or not package or project =~ /[^a-zA-Z0-9]/
  usage()
end

# Make sure the first letter is uppercased
if project[0] =~ /[a-z]/
  project = "#{project[0].upcase}#{project[1..-1]}"
end

path = "/src/#{project.downcase}"
activity = "#{project}Activity"


confirmation = <<END
Creating project with these parameters:
Project: #{project}
Path: #{path}
Activity: #{activity}
Package: #{package}
END

puts confirmation

command = "android create project --target android-19 --name #{project} --path #{path} --activity #{activity} --package #{package}"
puts "Command: #{command}"

`#{command}`

# Error:
#A problem occurred configuring root project 'foobar'.
#                                             > com.android.io.StreamException: java.io.FileNotFoundException: /src/foobar/src/main/AndroidManifest.xml (No such file or directory)

# Now, align for gradle
# FileUtils.mv
# FileUtils.cp '/src/example/build.gradle'


# Update local.properties
# Update build.gradle
# Update app/build.gradle
# Move directories to support gradle
FileUtils.mkdir "#{path}/app"
FileUtils.mkdir_p "#{path}/app/src/main/java"
FileUtils.mkdir_p "#{path}/app/src/main/res"
FileUtils.mv "#{path}/src", "#{path}/app/src/main/java/."
FileUtils.mv "#{path}/res", "#{path}/app/src/main/."
FileUtils.mv "#{path}/AndroidManifest.xml", "#{path}/app/src/main/."
FileUtils.cp "#{path}/../example/app/build.gradle", "app/."
FileUtils.cp "#{path}/../example/settings.gradle", "."


