#!/usr/bin/env ruby

require 'fileutils'

def usage
  puts "USAGE: create_android_with_gradle <project-name> <package-name>"
  puts
  puts "Use only [a-zA-Z0-9] in the project name"
  puts "Package name should be the java language package format: com.example.mything"
  puts
  exit	 
end 

project = ARGV.shift
package = ARGV.shift
if not project or not package or project =~ /[^a-zA-Z0-9]/
  usage()
end

# Make sure the first letter is uppercased
if project[0] =~ /[a-z]/
  project = "#{project[0].upcase}#{project[1..-1]}"
end

path = "/src/#{project.downcase}"
activity = "#{project}Activity"


confirmation = <<END
Creating project with these parameters:
Project: #{project}
Path: #{path}
Activity: #{activity}
Package: #{package}
END

puts confirmation

command = "android create project --target android-19 --name #{project} --path #{path} --activity #{activity} --package #{package}"
puts "Command: #{command}"

`#{command}`

FileUtils.mkdir_p "#{path}/app/src/main/java"
FileUtils.mv "#{path}/src", "#{path}/app/src/main/java/."
FileUtils.mv "#{path}/res", "#{path}/app/src/main/."
FileUtils.mv "#{path}/AndroidManifest.xml", "#{path}/app/src/main/."
FileUtils.cp "#{path}/../foobar/app/build.gradle", "#{path}/app/."
FileUtils.cp "#{path}/../foobar/build.gradle", "#{path}/."
FileUtils.cp "#{path}/../foobar/settings.gradle", "#{path}/."


